### PR TITLE
Fixes involving path of settings.py

### PR DESCRIPTION
**Pull request by paolopaolopaolo**
- include env.proj_name when pointing at settings.py
- fixed two breakpoints in the new project workflow

### CODE REVIEW

**Comment by paolopaolopaolo** [comment]
@rmutter, quick update to manticore-django! Please let me know if what I did was an actual solution or a bandaid solution or both.

**Comment by rmutter** [comment]
@paolopaolopaolo I'm concerned about this breaking any of our current projects and it might be preferable to make the location configurable with a smart default. Does that make sense?

@baylee here's what we were talking about - not sure if for deploying purposes there's more changes that would need to be made

**Comment by paolopaolopaolo** [comment]
@rmutter, how about the default using the old structure with a flag in vagrant.new that chooses when to do my changes in new projects with the new structure?

**Comment by rmutter** [comment]
@paolopaolopaolo to recap our verbal convo, yes I think that makes sense

**Comment by paolopaolopaolo** [comment]
@rmutter, made the changes we discussed! If you call vagrant.new without adding the flag, it will behave in the old manner. And the default is the old behavior, so starting any currently existing project should be fine.

**Pull request merged**
